### ISSUE TITLE
Add decoupling to pixi.js

### ISSUE THREAD

**Issue by wenq1** [pixijs/pixi-sound#60]
Maybe the module can decouple from PIXI.js (in global namespace) for ppl that do not use PIXI for rendering but pixi-sound for audio?

I think we could expose an interface in index.ts that allow passing an arbitary PIXI object (even empty), for example:

````
var customPIXI = {};
import PixiSound from 'pixi-sound';
PixiSound.init (customPIXI);
````

and in SoundLibrary.init (), just change:

````
public static init (customPIXI) {
    const PixiJS = customPIXI || PIXI as any;
}
````
Possible?

**Comment by bigtimebuddy** [comment]
This actually was the original design of this library. However, there are a bunch assumptions based on PIXI being available in the code. Because it's so closely tied as a plugin and in design to the PixiJS ecosystem, I don't think this is realistic right now to support this. I'm going to close this, but will re-open if there's a lot of enthusiasm to decouple this library from PixiJS.
