### ISSUE TITLE
PIXI-sound makes the phone slow

### ISSUE THREAD

**Issue by MarsCaiWORD** [pixijs/pixi-sound#78]
pixi-sound is good library
i use it on Develop mobile web pages  , but makes the phone slow 
Is there any way to improve performance?

**Comment by hypersurge** [comment]
Pixi-sound is a superb library.  We also experienced significant slowdown on mobile devices when the total number of Sound instances grew - very noticeable once exceeding 50.  We were also able to replicate the mobile issue using Chrome's "mid-tier mobile" developer tool setting.

From my understanding Pixi-sound adopts the strategy of keeping all WebAudioNodes connected, then cloning new ones when a sound is played.  An apparent drawback of such a strategy is the overhead of the non-playing nodes - in particular due to the ScriptProcessorNode.  Apart from connect(), disconnect() and some event listeners in WebAudioInstance I saw no other reference to the ScriptProcessorNode in the library.  No noticeable loss of functionality was apparent by removing it (we aren't using filters) whereas a significant performance boost was achieved without any ScriptProcessorNodes.

What purpose do the ScriptProcessorNodes achieve, what are we losing by removing them?  Should they stay?  Is there an alternative?

@MarsCaiWORD I've attached a patched minified version to see if it makes a difference for your scenario.
[patch.zip](https://github.com/pixijs/pixi-sound/files/2800386/patch.zip)

**Comment by ashleygwinnell** [comment]
@hypersurge Your patch might have just fixed an issue that I was having! 🎉 On the Samsung S8, when multiple sound sprites are loaded / in memory (e.g. one for each character), when re-focussing on the page after a blur event, the device was hanging for an amount of time proportionate to the amount of blurred time. e.g. 60 seconds of blur time was about a hang up of 5-10 seconds, and half an hour of blur time could hang for up to a minute or sometimes completely crash the browser. This patch file seems to have stopped that completely. :) 

So yes, it would be good to know if there are any limitations of having ScriptProcessorNodes removed.

**Comment by ashleygwinnell** [comment]
It does seem now that setting `paused` false/true on the sounds will not resume from where it was paused but instead restart from the beginning.

**Comment by bigtimebuddy** [comment]
The ScriptProcessorNode provides a reliable update callback. But I’m sure we could just use Pixi’s ticker instead. The nice thing about the SPN is that it handles context being paused/resume. There are definitely more preformant options for this.

**Comment by bigtimebuddy** [comment]
I think this is the only place where the script node is used:
https://github.com/pixijs/pixi-sound/blob/9f18e27997e5153fe8ef04a36e4489e986b180d9/src/webaudio/WebAudioInstance.ts#L401-L411

**Comment by bigtimebuddy** [comment]
Made the use of `ScriptProcessNode` opt-in with #105. This should improve mobile performance.
